apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: spot-termination-notice-handler
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: spot-termination-notice-handler
      name: spot-termination-notice-handler
    spec:
      containers:
      - image: camil/kube-spot-termination-notice-handler:1.6.3
        imagePullPolicy: Always
        name: spot-termination-notice-handler
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      imagePullSecrets:
        - name: dockerhubkey
