apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
  namespace: log
data:
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>

    ################################################################################################################
    ##########################################   Custom Configuration    #######################################################

    ##### Example App 1 #####
    <source>
      @type tail
      path /var/log/containers/example-app-1-*
      pos_file /logpos/example-app-1.log.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag example-app-1.*
      format json
      read_from_head true
    </source>

    <filter example-app-1.**>
      @type kubernetes_metadata
    </filter>

    <filter example-app-1.**>
      @type record_transformer
      <record>
        hostname ${hostname}
      </record>
    </filter>

    <match example-app-1.**>
      @type cloudwatch_logs
      log_group_name "Production/ExampleApp1"
      use_tag_as_stream true
      remove_log_group_name_key true
      auto_create_stream true
      put_log_events_retry_limit 20
    </match>
    ################################################################################################################


    ##### Example App 2 #####
    <source>
      @type tail
      path /var/log/containers/example-app-2-*
      pos_file /logpos/example-app-2.log.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag example-app-2.*
      format json
      read_from_head true
    </source>

    <filter example-app-2.**>
      @type kubernetes_metadata
    </filter>

    <filter example-app-2.**>
      @type record_transformer
      <record>
        hostname ${hostname}
      </record>
    </filter>

    <match example-app-2.**>
      @type cloudwatch_logs
      log_group_name "Production/ExampleApp2"
      use_tag_as_stream true
      remove_log_group_name_key true
      auto_create_stream true
      put_log_events_retry_limit 20
    </match>
    ################################################################################################################
